### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [FiReLScar/FiReLScar#1]

**Comment by Foxxy-01** [comment]
Lol just curious do u run linux or windows I am trying to move to ubuntu linux

It's me inker splatz btw lol

**Comment by Foxxy-01** [comment]
If u want me to leave u alone i will, I just wanted to say hi lol

**Comment by FiReLScar** [comment]
You're still trying to contact me after like three fucking years? Chill the fuck out and touch grass, I don't even remember why I removed you, I don't care if I did, I had a reason, go make some friends ffs.

**Comment by ghost** [comment]
Just saying I was trolling you, not trying to contact you I not to be rude don't care about you anymore lmao (don't respond to this btw lol I was just looking at my issues on github and just wanted to clear this up)
